### ISSUE TITLE
Conv2d not working for kernel size other than 3x3

### ISSUE THREAD

**Issue by PreetX-Amin** [dabeschte/DeltaCNN#2]
First of all, thank you for your amazing work.

I am trying to run this example code:
```python
import torch
import deltacnn as dc

model = torch.nn.Sequential(dc.DCSparsify(), dc.DCConv2d(3, 128, (7,7), 2, padding=2, bias=False), dc.DCDensify()).to('cuda')
t = 100*torch.rand(size=(1, 3, 128, 128)).to('cuda')

out = model(t)
```

for every kernel size other than 3x3 it gives the following error:

`RuntimeError: Caught an unknown exception!`

Please help!!

**Comment by dabeschte** [comment]
There are multiple problems with the code. DeltaCNN required channels last memory format for input tensors and the weights are reordered in a special way which is much more efficient to access in convolutions than PyTorch's standard weight layout.

Please read the readme.txt carefully to understand how to use DeltaCNN properly.

Your example network needs to be written as follows:
```
import torch
import deltacnn as dc

class Model(dc.DCModule):
    def __init__(self):
        super().__init__()
        self.layers = torch.nn.Sequential(dc.DCSparsify(), dc.DCConv2d(3, 128, (7,7), 2, padding=2, bias=False), dc.DCDensify())

    def forward(self, x):
        return self.layers(x)

model = Model().to('cuda', memory_format=torch.channels_last)
model.process_filters()
t = 100*torch.rand(size=(1, 64, 128, 128)).to('cuda').contiguous(memory_format=torch.channels_last)

out = model(t)
```

**Comment by PreetX-Amin** [comment]
Thank you for your quick response. I was trying to implement ResNET backbone and was getting this error. I will try to integrate this solution into my code. Thank you again.
