### ISSUE TITLE
Encountering RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by PreetX-Amin** [dabeschte/DeltaCNN#4]
I am trying to train ResNet101 backbone for my mask-rcnn network. During training, after some iteration, (sometimes 2 sometimes 4, mostly 2) session crashes without any errors. After some debugging, I have narrowed it down to `line 1259` of `sparse_layers.py` in `DCSparsify` class.
```python
sparsify(input, self.prev_in, x, self.mask, threshold)
```
I tried to print all input arguments of this function before and after this line and I got `RuntimeError: CUDA error: an illegal memory access was encountered`. Since I don't have much experience in programming in Cuda c/c++, I couldn't debug further. Please help.

**Comment by dabeschte** [comment]
DeltaCNN does not support training. While I think that something else of the configuration might also be causing this error, the solution to training is to set DCConv2d.backend = DCBackend.cudnn

**Comment by dabeschte** [comment]
Oh, are you using the delta_cudnn backend?

**Comment by PreetX-Amin** [comment]
Setting `DCConv2d.backend = DCBackend.cudnn` seems to do the trick but now I am facing following error
```
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
```

Can you provide some solutions?

**Comment by PreetX-Amin** [comment]
Also, I had to train the network again because loading pre-trained weights after converting them into `torch.channel_last` format didn't give the same result

**Comment by dabeschte** [comment]
You should not have to retrain a model. Reusing the pretrained weights should always work unless you discovered a bug in my framwork or have a bug in your port.
Could you send me the original and deltacnn version that you are using? I am currently on sick leave, but I can take a look at it next week if you haven't found a solution

**Comment by dabeschte** [comment]
Did you already find a solution to your problem?

**Comment by PreetX** [comment]
Yes I have reviewed my code for ResNet and solved the issue. I am still not able to train for DeltaCNN layers but loading pretrained networks works now.

Thanks for all your support.

**Comment by dabeschte** [comment]
Good to hear that loading pretrained weights is working at least.

I just saw that you are implementing DeltaCNN into Detectron2. I really support this, especially if it remains open source. I will take a look at the training issues and hope that we can sort that out.

**Comment by PreetX-Amin** [comment]
Yes I have reviewed my code for ResNet and solved the issue. I am still not able to train for DeltaCNN layers but loading pretrained networks works now.

Thanks for all your support.

**Comment by PreetX-Amin** [comment]
I will commit my final code with additional details to GitHub repo if you have some time please check that out later
