### ISSUE TITLE
 In 16 bit mode, the output value after the 4th frame is NAN

### ISSUE THREAD

**Issue by jiaerwang0328** [dabeschte/DeltaCNN#6]
I use the following code to run in 16-bit mode：
```
original_model.to(torch.float16)
dc_model.to(torch.float16)
input_batch.to(torch.float16)
```
But ,I get the correct resul tin 32 bit mode.
output :
```
original: 37.60ms, dc: 43.09ms box_diff_mean=0.060     
original: 32.77ms, dc: 27.92ms box_diff_mean=0.073     
original: 32.87ms, dc: 30.71ms box_diff_mean=0.097     
original: 32.24ms, dc: 32.57ms box_diff_mean=nan
```

**Comment by dabeschte** [comment]
Sorry, but it is impossible to help you with the problem when you don't provide more info.
You can try to debug it by providing custom input images? e.g. first image is all zeros and second image is all ones.
Also, DeltaCNN does not support tensor cores. So it could be that cuDNN inference outperforms DeltaCNN greatly in float16 depending on your hardware. We do not plan to add support for tensor cores. Float16 was only needed to get DeltaCNN working on the low-end Jetson Nano.

**Comment by jiaerwang0328** [comment]
Thanks for your reply, I want to make DeltaCNN run on low-end devices like nano or nx. When I found out during debugging that in float16 mode, DCConcatenate doesn't seem right. E.g
```
import torch
from deltacnn.sparse_layers import DCSparsify, DCMaxPooling, DCModule, DCConv2d, DCDensify, DCConcatenate
def genTestData():
    inC, inH, inW = 128, 304, 304#3, 15, 20
    input = torch.randn(1, inC, inH, inW).cuda()
    prevInput = torch.randn(1, inC, inH, inW).cuda()
    return input, prevInput

input, prevInput = genTestData()
class my_net(DCModule):
    def __init__(self):
        super(my_net, self).__init__()
        self.to_s = DCSparsify(delta_threshold=0.0)
        self.cat = DCConcatenate()
        self.ds = DCDensify()
    def _forward_impl(self, x):
        x = self.to_s(x)  # added
        x = self.cat(x, x)
        return self.ds(x)

    def forward(self, x):
        return self._forward_impl(x)

model = my_net()
model = model.cuda()
model = model.to(torch.float16)
model.process_filters()

prevInput = prevInput.to(torch.float16)
input = input.to(torch.float16)
prevInput_out = model(prevInput)
input_out = model(input)

print(prevInput)
print(prevInput_out)
print(input)
print(input_out)
```

**Comment by dabeschte** [comment]
Thanks, that was a very helpful example. Should be fixed now. Please pull and run `python setup.py install` again
